name: holo_streams
description: An app built with Flutter that displays current and upcoming Hololive streams.

publish_to: 'none'

version: 3.4.0+41

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.2
  intl: ^0.17.0
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  google_mobile_ads: ^5.0.0
  dart_holodex_api: ^2.0.0
  material_symbols_icons: ^4.2668.0
  skeletonizer: ^0.7.0
  collection: ^1.17.2
  flutter_linkify: ^6.0.0
  get: ^4.6.6
  easy_refresh: ^3.3.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
